In [1]:
# just extenstion to python for multi-dimensional array support and maths calculations on these arrays
import numpy as np

In [2]:
x=[1,2,3,4,5]
a=np.array(x)

In [26]:
a[1:3]

array([2, 3])

In [10]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x=np.arange(1,2, 0.1)
x

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [24]:
b=np.array([[1,1],[2,2]])
b.ndim

2

In [25]:
np.shape(b)

(2, 2)

In [34]:
a=np.random.randn(1,2)
a

array([[-0.08900395,  1.04183869]])